-- Phase 2: seed all Telangana mandals (589) across 33 districts.
-- Requires phase 1 districts. Idempotent on (district_id, slug).
-- Source: OSM / LGD-aligned Subdistricts_in_Telangana directory.
-- Keep in sync with src/lib/data/mandals-directory.json
-- Notes: Warangal Urban → hanumakonda; Warangal Rural → warangal.
-- Slug aliases for existing hubs: Kodada→kodad, Thallada→tallada.

WITH d AS (SELECT id, slug FROM districts),
v(district_slug, slug, name_en, name_te, lgd_code) AS (
  VALUES
    ('adilabad', 'adilabad-urban', 'Adilabad Urban', 'ఆదిలాబాద్ (అర్బన్)', '4306'),
    ('adilabad', 'aidilabad-rural', 'Aidilabad Rural', 'ఆదిలాబాద్ (రూరల్)', '6221'),
    ('adilabad', 'bazarhatnoor', 'Bazarhatnoor', 'బజార్ హత్నూర్', '4323'),
    ('adilabad', 'bela', 'Bela', 'బేల', '4308'),
    ('adilabad', 'bheempur', 'Bheempur', 'భీంపూర్', '6223'),
    ('adilabad', 'boath', 'Boath', 'బోథ్', '4324'),
    ('adilabad', 'gadiguda', 'Gadiguda', 'గాదిగూడ', '6225'),
    ('adilabad', 'gudihatnoor', 'Gudihatnoor', 'గుడిహత్నూర్', '4310'),
    ('adilabad', 'ichoda', 'Ichoda', 'ఇచ్చోడ', '4322'),
    ('adilabad', 'inderavelly', 'Inderavelly', 'ఇందర్ వెల్లి', '4311'),
    ('adilabad', 'jainath', 'Jainath', 'జైనధ్', '4307'),
    ('adilabad', 'mavala', 'Mavala', 'మావల', '6222'),
    ('adilabad', 'narnoor', 'Narnoor', 'నార్నూర్', '4312'),
    ('adilabad', 'neradigonda', 'Neradigonda', 'నేరడిగొండ', '4325'),
    ('adilabad', 'sirikonda', 'Sirikonda', 'సిరికొండ', '6224'),
    ('adilabad', 'talamadugu', 'Talamadugu', 'తలమడుగు', '4309'),
    ('adilabad', 'tamsi', 'Tamsi', 'తాంసి', '4305'),
    ('adilabad', 'utnoor', 'Utnoor', 'ఉట్నూర్', '4321'),
    ('bhadradri-kothagudem', 'allapalli', 'Allapalli', 'ఆళ్ళపల్లి', '6267'),
    ('bhadradri-kothagudem', 'annapureddypalli', 'Annapureddypalli', 'అన్నపురెడ్డిపల్లి', '6268'),
    ('bhadradri-kothagudem', 'aswapuram', 'Aswapuram', 'అశ్వాపురం', '4728'),
    ('bhadradri-kothagudem', 'aswaraopeta', 'Aswaraopeta', 'అశ్వారావుపేట', '4749'),
    ('bhadradri-kothagudem', 'bhadrachalam', 'Bhadrachalam', 'భద్రాచలం', '4730'),
    ('bhadradri-kothagudem', 'burgampahad', 'Burgampahad', 'బూర్గంపాడు', '4736'),
    ('bhadradri-kothagudem', 'chandrugonda', 'Chandrugonda', 'చండ్రుగొండ', '4747'),
    ('bhadradri-kothagudem', 'cherla', 'Cherla', 'చర్ల', '4726'),
    ('bhadradri-kothagudem', 'chunchupalli', 'Chunchupalli', 'చుంచుపల్లి', '6376'),
    ('bhadradri-kothagudem', 'dammapeta', 'Dammapeta', 'దమ్మపేట', '4750'),
    ('bhadradri-kothagudem', 'dummugudem', 'Dummugudem', 'దుమ్ముగూడెం', '4729'),
    ('bhadradri-kothagudem', 'gundala', 'Gundala', 'గుండాల', '4741'),
    ('bhadradri-kothagudem', 'julurpadu', 'Julurpadu', 'జూలురుపాడు', '4746'),
    ('bhadradri-kothagudem', 'karakagudem', 'Karakagudem', 'కరకగూడెం', '6269'),
    ('bhadradri-kothagudem', 'kothagudem', 'Kothagudem', 'కొత్తగూడెం', '4738'),
    ('bhadradri-kothagudem', 'laxmidevipalli', 'Laxmidevipalli', 'లక్ష్మీదేవిపల్లి', '6266'),
    ('bhadradri-kothagudem', 'manuguru', 'Manuguru', 'మణుగూరు', '4727'),
    ('bhadradri-kothagudem', 'mulkalapally', 'Mulkalapally', 'ములకలపల్లి', '4748'),
    ('bhadradri-kothagudem', 'palvoncha', 'Palvoncha', 'పాల్వంచ', '4737'),
    ('bhadradri-kothagudem', 'pinapaka', 'Pinapaka', 'పినపాక', '4725'),
    ('bhadradri-kothagudem', 'sujathanagar', 'Sujathanagar', 'సుజాతనగర్', '6265'),
    ('bhadradri-kothagudem', 'tekulapalli', 'Tekulapalli', 'టేకులపల్లి', '4739'),
    ('bhadradri-kothagudem', 'yellandu', 'Yellandu', 'ఎల్లందు', '4740'),
    ('hanumakonda', 'bheemadevarpalli', 'Bheemadevarpalli', 'భీందేవరపల్లి', '4448'),
    ('hanumakonda', 'dharmasagar', 'Dharmasagar', 'ధర్మసాగర్', '4677'),
    ('hanumakonda', 'elkathurthy', 'Elkathurthy', 'ఎల్కతుర్తి', '4449'),
    ('hanumakonda', 'hanamkonda', 'Hanamkonda', 'హన్మకొండ', '4695'),
    ('hanumakonda', 'hasanparthy', 'Hasanparthy', 'హసన్ పర్తి', '4678'),
    ('hanumakonda', 'inavole', 'Inavole', 'ఐనవోలు', '6249'),
    ('hanumakonda', 'kamalapur', 'Kamalapur', 'కమలాపూర్', '4447'),
    ('hanumakonda', 'khazipet', 'Khazipet', 'కాజిపేట', '6247'),
    ('hanumakonda', 'khila-warangal', 'Khila Warangal', 'ఖిలా వరంగల్', '6246'),
    ('hanumakonda', 'velair', 'Velair', 'వేలేరు', '6252'),
    ('hanumakonda', 'warangal', 'Warangal', 'వరంగల్', '4706'),
    ('hyderabad', 'amberpet', 'Amberpet', 'అంబర్ పేట్', '4502'),
    ('hyderabad', 'ameerpet', 'Ameerpet', 'అమీర్ పేట్', '4497'),
    ('hyderabad', 'asif-nagar', 'Asif Nagar', 'ఆసిఫ్ నగర్', '4506'),
    ('hyderabad', 'bahadurpura', 'Bahadurpura', 'బహదూర్ పుర', '4508'),
    ('hyderabad', 'bandlaguda', 'Bandlaguda', 'బండ్లగూడ', '4509'),
    ('hyderabad', 'charminar', 'Charminar', 'చార్మినార్', '4510'),
    ('hyderabad', 'golconda', 'Golconda', 'గోల్కొండ', '4507'),
    ('hyderabad', 'himayatnagar', 'Himayatnagar', 'హిమాయత్ నగర్', '4503'),
    ('hyderabad', 'khairatabad', 'Khairatabad', 'ఖైరతాబాద్', '4505'),
    ('hyderabad', 'marredpally', 'Marredpally', 'మారెడ్ పల్లి', '4500'),
    ('hyderabad', 'musheerabad', 'Musheerabad', 'ముషీరాబాద్', '4501'),
    ('hyderabad', 'nampally', 'Nampally', 'నాంపల్లి', '4504'),
    ('hyderabad', 'saidabad', 'Saidabad', 'సైదాబాద్', '4511'),
    ('hyderabad', 'secunderabad', 'Secunderabad', 'సికింద్రాబాద్', '4498'),
    ('hyderabad', 'shaikpet', 'Shaikpet', 'షేక్ పేట్', '4496'),
    ('hyderabad', 'tirumalgiri', 'Tirumalgiri', 'తిరుమలగిరి', '4499'),
    ('jagtial', 'beerpur', 'Beerpur', 'బీర్ పూర్', '6212'),
    ('jagtial', 'buggaram', 'Buggaram', 'బుగ్గారం', '6213'),
    ('jagtial', 'dharmapuri', 'Dharmapuri', 'ధర్మపురి', '4397'),
    ('jagtial', 'gollapalli', 'Gollapalli', 'గొల్లపల్లి', '4412'),
    ('jagtial', 'ibrahimpatnam', 'Ibrahimpatnam', 'ఇబ్రహీంపట్నం', '4393'),
    ('jagtial', 'jagitial', 'Jagitial', 'జగిత్యాల్', '4414'),
    ('jagtial', 'jagitial-rural', 'Jagitial Rural', 'జగిత్యాల రూరల్', '6211'),
    ('jagtial', 'kathlapur', 'Kathlapur', 'కథలాపూర్', '4418'),
    ('jagtial', 'kodimial', 'Kodimial', 'కొడిమ్యాల', '4420'),
    ('jagtial', 'korutla', 'Korutla', 'కోరుట్ల', '4416'),
    ('jagtial', 'mallapur', 'Mallapur', 'మల్లాపూర్', '4394'),
    ('jagtial', 'mallial', 'Mallial', 'మల్యాల', '4413'),
    ('jagtial', 'medipalli', 'Medipalli', 'మేడిపల్లి', '4415'),
    ('jagtial', 'metpalli', 'Metpalli', 'మెట్ పల్లి', '4417'),
    ('jagtial', 'pegadapalli', 'Pegadapalli', 'పెగడపల్లి', '4421'),
    ('jagtial', 'raikal', 'Raikal', 'రాయికల్', '4395'),
    ('jagtial', 'sarangapur', 'Sarangapur', 'సారంగాపూర్', '4396'),
    ('jagtial', 'velgatur', 'Velgatur', 'వెల్గటూరు', '4398'),
    ('jangaon', 'bachannapet', 'Bachannapet', 'బచ్చన్నపేట', '4674'),
    ('jangaon', 'chilpur', 'Chilpur', 'చిల్పూర్', '6259'),
    ('jangaon', 'devaruppula', 'Devaruppula', 'దేవరుప్పుల', '4701'),
    ('jangaon', 'ghanpur-station', 'Ghanpur (Station)', 'ఘణపూర్(స్టేషన్)', '4676'),
    ('jangaon', 'gundala', 'Gundala', 'గుండాల', '4618'),
    ('jangaon', 'jangoan', 'Jangoan', 'ఙనగామ', '4699'),
    ('jangaon', 'kodakandla', 'Kodakandla', 'కొడకండ్ల', '4702'),
    ('jangaon', 'lingalaghanpur', 'LingalaGhanpur', 'లింగాలఘణపూర్', '4700'),
    ('jangaon', 'narmetta', 'Narmetta', 'నర్మెట్ట', '4675'),
    ('jangaon', 'palakurthy', 'Palakurthy', 'పాలకుర్తి', '4697'),
    ('jangaon', 'ragunathpally', 'Ragunathpally', 'రఘునాథపల్లి', '4698'),
    ('jangaon', 'tharigoppula', 'Tharigoppula', 'తరిగొప్పుల', '6257'),
    ('jangaon', 'zaffergadh', 'Zaffergadh', 'జఫర్ గడ్', '4696'),
    ('jayashankar-bhupalpally', 'bhupalpally', 'Bhupalpally', 'భూపాల్ పల్లి', '4682'),
    ('jayashankar-bhupalpally', 'chityal', 'Chityal', 'చిట్యాల', '4681'),
    ('jayashankar-bhupalpally', 'ghanpur-mulug', 'Ghanpur (Mulug)', 'ఘణపూర్ (ములుగు)', '4683'),
    ('jayashankar-bhupalpally', 'kataram', 'Kataram', 'కాటారం', '4402'),
    ('jayashankar-bhupalpally', 'mahadevpur', 'Mahadevpur', 'మహాదేవపూర్', '4403'),
    ('jayashankar-bhupalpally', 'malharrao', 'Malharrao', 'మల్హార్ రావు', '4405'),
    ('jayashankar-bhupalpally', 'mogullapally', 'Mogullapally', 'మొగుళ్ళపల్లి', '4680'),
    ('jayashankar-bhupalpally', 'mutharam-mahadevpur', 'Mutharam Mahadevpur', 'ముత్తారం (మహదేవ్ పూర్)', '4404'),
    ('jayashankar-bhupalpally', 'palimela', 'Palimela', 'పల్మెల', '6250'),
    ('jayashankar-bhupalpally', 'regonda', 'Regonda', 'రేగోండ', '4690'),
    ('jayashankar-bhupalpally', 'tekumatla', 'Tekumatla', 'టేకుమట్ల', '6248'),
    ('jogulamba-gadwal', 'alampur', 'Alampur', 'ఆలంపూర్', '4612'),
    ('jogulamba-gadwal', 'dharoor', 'Dharoor', 'ధరూర్', '4591'),
    ('jogulamba-gadwal', 'gadwal', 'Gadwal', 'గద్వాల్', '4603'),
    ('jogulamba-gadwal', 'ghattu', 'Ghattu', 'గట్టు', '4605'),
    ('jogulamba-gadwal', 'ieeja', 'Ieeja', 'అయిజ', '4606'),
    ('jogulamba-gadwal', 'itikyala', 'Itikyala', 'ఇటిక్యాల', '4607'),
    ('jogulamba-gadwal', 'kaloor-thimmandoddi', 'Kaloor Thimmandoddi', 'కలూరి తిమ్మన్ దొడ్డి', '6297'),
    ('jogulamba-gadwal', 'maldakal', 'Maldakal', 'మల్దకల్', '4604'),
    ('jogulamba-gadwal', 'manopad', 'Manopad', 'మనాపడ్', '4611'),
    ('jogulamba-gadwal', 'rajoli', 'Rajoli', 'రాజోలి', '6296'),
    ('jogulamba-gadwal', 'undavelly', 'Undavelly', 'ఉండవెల్లి', '6299'),
    ('jogulamba-gadwal', 'waddepally', 'Waddepally', 'వడ్డెపల్లి', '4610'),
    ('kamareddy', 'banswada', 'Banswada', 'బాన్స్ వాడ', '4383'),
    ('kamareddy', 'bhiknoor', 'Bhiknoor', 'బిక్ నూర్', '4391'),
    ('kamareddy', 'bibipet', 'Bibipet', 'బీబీపేట్', '6242'),
    ('kamareddy', 'bichkunda', 'Bichkunda', 'బిచ్కుంద', '4374'),
    ('kamareddy', 'birkur', 'Birkur', 'బీర్కూర్', '4375'),
    ('kamareddy', 'domakonda', 'Domakonda', 'దోమకొండ', '4392'),
    ('kamareddy', 'gandhari', 'Gandhari', 'గాందారి', '4382'),
    ('kamareddy', 'jukkal', 'Jukkal', 'జుక్కల్', '4373'),
    ('kamareddy', 'kamareddy', 'Kamareddy', 'కామారెడ్డి', '4390'),
    ('kamareddy', 'lingampet', 'Lingampet', 'లింగంపేట్', '4388'),
    ('kamareddy', 'machareddy', 'Machareddy', 'మాచారెడ్డి', '4380'),
    ('kamareddy', 'madnoor', 'Madnoor', 'మద్నూర్', '4372'),
    ('kamareddy', 'nagireddypet', 'Nagireddypet', 'నాగిరెడ్డిపెట్', '4387'),
    ('kamareddy', 'nasurullabad', 'Nasurullabad', 'నసురుల్లాబాద్', '6244'),
    ('kamareddy', 'nizamsagar', 'Nizamsagar', 'నిజాంసాగర్', '4385'),
    ('kamareddy', 'pedda-kodapgal', 'Pedda Kodapgal', 'పెద్ద కోడపగల్', '6245'),
    ('kamareddy', 'pitlam', 'Pitlam', 'పిట్లం', '4384'),
    ('kamareddy', 'rajampet', 'Rajampet', 'రాజంపెట్', '6241'),
    ('kamareddy', 'ramareddy', 'Ramareddy', 'రామారెడ్డి', '6243'),
    ('kamareddy', 'sadashivanagar', 'Sadashivanagar', 'సదాశివ్ నగర్', '4381'),
    ('kamareddy', 'tadwai', 'Tadwai', 'తాడ్వాయి', '4389'),
    ('kamareddy', 'yellareddy', 'Yellareddy', 'ఎల్లారెడ్డి', '4386'),
    ('karimnagar', 'chigurumamidi', 'Chigurumamidi', 'చిగురుమామిడి', '4442'),
    ('karimnagar', 'choppadandi', 'Choppadandi', 'చొప్పదండి', '4424'),
    ('karimnagar', 'ellandakunta', 'Ellandakunta', 'ఇల్లంతకుంట', '6234'),
    ('karimnagar', 'gangadhara', 'Gangadhara', 'గంగాధర', '4422'),
    ('karimnagar', 'ganneruvaram', 'Ganneruvaram', 'గన్నేరువరం', '6232'),
    ('karimnagar', 'huzurabad', 'Huzurabad', 'హుజురాబాద్', '4446'),
    ('karimnagar', 'jammikunta', 'Jammikunta', 'జమ్మికుంట', '4440'),
    ('karimnagar', 'karimnagar', 'Karimnagar', 'కరీంనగర్', '6231'),
    ('karimnagar', 'karimnagar-rural', 'Karimnagar Rural', 'Karimnagar Rural మండలం', '4428'),
    ('karimnagar', 'kothapally', 'Kothapally', 'Kothapally మండలం', '6230'),
    ('karimnagar', 'manakondur', 'Manakondur', 'మానకొండూర్', '4427'),
    ('karimnagar', 'ramadugu', 'Ramadugu', 'రామడుగు', '4423'),
    ('karimnagar', 'shankarapatnam', 'Shankarapatnam', 'శంకరపట్నం', '4441'),
    ('karimnagar', 'thimmapur-lmd', 'Thimmapur LMD', 'Thimmapur LMD మండలం', '4438'),
    ('karimnagar', 'v-saidapur', 'V.Saidapur', 'సైదాపూర్', '4445'),
    ('karimnagar', 'veenavanka', 'Veenavanka', 'వీణవంక', '4439'),
    ('khammam', 'bonakal', 'Bonakal', 'బోనకల్', '4765'),
    ('khammam', 'chinthakani', 'Chinthakani', 'చింతకాని', '4760'),
    ('khammam', 'enkoor', 'Enkoor', 'ఏనుకూరు', '4753'),
    ('khammam', 'kalluru', 'Kalluru', 'కల్లూరు', '4763'),
    ('khammam', 'kamepalli', 'Kamepalli', 'కామేపల్లి', '4745'),
    ('khammam', 'khammam-rural', 'Khammam (Rural)', 'ఖమ్మం రూరల్', '4756'),
    ('khammam', 'khammam-urban', 'Khammam Urban', 'ఖమ్మం అర్బన్', '6326'),
    ('khammam', 'konijerla', 'Konijerla', 'కొణిజర్ల', '4761'),
    ('khammam', 'kusumanchi', 'Kusumanchi', 'కూసుమంచి', '4755'),
    ('khammam', 'madhira', 'Madhira', 'మధిర', '4766'),
    ('khammam', 'mudigonda', 'Mudigonda', 'ముదిగొండ', '4758'),
    ('khammam', 'nelakondapalli', 'Nelakondapalli', 'నేలకొండపల్లి', '4759'),
    ('khammam', 'penuballi', 'Penuballi', 'పెనుబల్లి', '4752'),
    ('khammam', 'raghunadhapalem', 'Raghunadhapalem', 'రఘునాథపాలెం', '4757'),
    ('khammam', 'sathupalli', 'Sathupalli', 'సత్తుపల్లి', '4751'),
    ('khammam', 'singareni', 'Singareni', 'సింగరేణి', '4744'),
    ('khammam', 'tallada', 'Thallada', 'తల్లాడ', '4762'),
    ('khammam', 'tirumalayapalem', 'Tirumalayapalem', 'తిరుమలాయపాలెం', '4754'),
    ('khammam', 'vemsoor', 'Vemsoor', 'వేంసూరు', '4768'),
    ('khammam', 'wyra', 'Wyra', 'వైరా', '4764'),
    ('khammam', 'yerrupalem', 'Yerrupalem', 'ఎర్రుపాలెం', '4767'),
    ('kumuram-bheem-asifabad', 'asifabad', 'Asifabad', 'ఆసిఫాబాద్', '4319'),
    ('kumuram-bheem-asifabad', 'bejjur', 'Bejjur', 'బెజ్జూర్', '4317'),
    ('kumuram-bheem-asifabad', 'chintalamanepally', 'Chintalamanepally', 'చింతాల మానెపల్లి', '6314'),
    ('kumuram-bheem-asifabad', 'dahegoan', 'Dahegoan', 'దహెగాం', '4329'),
    ('kumuram-bheem-asifabad', 'jainoor', 'Jainoor', 'జైనూర్', '4320'),
    ('kumuram-bheem-asifabad', 'kagaznagar', 'Kagaznagar', 'కాగజ్ నగర్', '4318'),
    ('kumuram-bheem-asifabad', 'kerameri', 'Kerameri', 'కెరమెరి', '4313'),
    ('kumuram-bheem-asifabad', 'koutala', 'Koutala', 'కౌటాల', '4316'),
    ('kumuram-bheem-asifabad', 'lingapur', 'Lingapur', 'లింగాపూర్', '6311'),
    ('kumuram-bheem-asifabad', 'penchicalpet', 'Penchicalpet', 'పెంచికల్ పేట్', '6313'),
    ('kumuram-bheem-asifabad', 'rebbena', 'Rebbena', 'రెబ్బెన', '4327'),
    ('kumuram-bheem-asifabad', 'sirpur-t', 'Sirpur (T)', 'సిర్పూర్ (టి)', '4315'),
    ('kumuram-bheem-asifabad', 'sirpur-u', 'Sirpur U', 'సిర్పూర్ ( యు )', '4326'),
    ('kumuram-bheem-asifabad', 'tiryani', 'Tiryani', 'తిర్యాని', '4333'),
    ('kumuram-bheem-asifabad', 'wankidi', 'Wankidi', 'వాంకిడి', '4314'),
    ('mahabubabad', 'bayyaram', 'Bayyaram', 'బయ్యారం', '4742'),
    ('mahabubabad', 'chinnagudur', 'Chinnagudur', 'చిన్నగూడూర్', '6254'),
    ('mahabubabad', 'danthalapalle', 'Danthalapalle', 'దంతాలపల్లి', '6255'),
    ('mahabubabad', 'dornakal', 'Dornakal', 'డోర్నకల్', '4722'),
    ('mahabubabad', 'gangaram', 'Gangaram', 'గంగారం', '6253'),
    ('mahabubabad', 'garla', 'Garla', 'గార్ల', '4743'),
    ('mahabubabad', 'gudur', 'Gudur', 'గూడూర్', '4711'),
    ('mahabubabad', 'kesamudram', 'Kesamudram', 'కేసముద్రం', '4717'),
    ('mahabubabad', 'kothaguda', 'Kothaguda', 'కొత్తగూడ', '4710'),
    ('mahabubabad', 'kuravi', 'Kuravi', 'కురవి', '4721'),
    ('mahabubabad', 'mahabubabad', 'Mahabubabad', 'మహబూబాబాద్', '4718'),
    ('mahabubabad', 'maripeda', 'Maripeda', 'మరిపెడ', '4720'),
    ('mahabubabad', 'narsimhulapet', 'Narsimhulapet', 'నర్సింహులపేట', '4719'),
    ('mahabubabad', 'nellikudur', 'Nellikudur', 'నెల్లికుదురు', '4716'),
    ('mahabubabad', 'peddavangara', 'Peddavangara', 'పెద్దవంగర', '6256'),
    ('mahabubabad', 'thorrur', 'Thorrur', 'తొర్రూర్', '4715'),
    ('mahabubnagar', 'addakal', 'Addakal', 'అడ్డాకల్', '4586'),
    ('mahabubnagar', 'balanagar', 'Balanagar', 'బాలనగర్', '4557'),
    ('mahabubnagar', 'bhoothpur', 'Bhoothpur', 'బూత్పూర్', '4574'),
    ('mahabubnagar', 'chinnachintakunta', 'Chinnachintakunta', 'చిన్నచింతకుంట', '4587'),
    ('mahabubnagar', 'devarakadra', 'Devarakadra', 'దేవర కద్ర', '4573'),
    ('mahabubnagar', 'gandeed', 'Gandeed', 'గండీడ్(M)', '4538'),
    ('mahabubnagar', 'hanwada', 'Hanwada', 'హన్వాడ', '4555'),
    ('mahabubnagar', 'jadcherla', 'Jadcherla', 'జడ్చర్ల', '4567'),
    ('mahabubnagar', 'koilkonda', 'Koilkonda', 'కోయిల్ కోండ', '4569'),
    ('mahabubnagar', 'mahabubnagar-rural', 'Mahabubnagar Rural', 'మహబూబ్ నగర్ (రూరల్)', '6258'),
    ('mahabubnagar', 'mahabubnagar-urban', 'Mahabubnagar Urban', 'మహబూబ్ నగర్ (అర్బన్)', '4568'),
    ('mahabubnagar', 'midjil', 'Midjil', 'మిడ్జిల్', '4566'),
    ('mahabubnagar', 'moosapet', 'Moosapet', 'మూసాపేట్', '6260'),
    ('mahabubnagar', 'nawabpet', 'Nawabpet', 'నవాబ్ పేట', '4556'),
    ('mahabubnagar', 'rajapur', 'Rajapur', 'రాజాపూర్', '6261'),
    ('mancherial', 'bellampally', 'Bellampally', 'బెల్లంపల్లి', '4350'),
    ('mancherial', 'bheemaram', 'Bheemaram', 'భీమారం', '6228'),
    ('mancherial', 'bheemini', 'Bheemini', 'భీమిని', '4328'),
    ('mancherial', 'chennur', 'Chennur', 'చెన్నూర్', '4356'),
    ('mancherial', 'dandepally', 'Dandepally', 'దండెపల్లి', '4348'),
    ('mancherial', 'hajipur', 'Hajipur', 'హజిపూర్', '6227'),
    ('mancherial', 'jaipur', 'Jaipur', 'జైపూర్', '4355'),
    ('mancherial', 'jannaram', 'Jannaram', 'జన్నారం', '4334'),
    ('mancherial', 'kannepally', 'Kannepally', 'కన్నేపల్లి', '6229'),
    ('mancherial', 'kasipet', 'Kasipet', 'కాసిపేట్', '4349'),
    ('mancherial', 'kotapally', 'Kotapally', 'కోటపల్లి', '4351'),
    ('mancherial', 'luxettipet', 'Luxettipet', 'లక్సెట్టిపేట్', '4353'),
    ('mancherial', 'mancherial', 'Mancherial', 'మంచిర్యాల్', '4354'),
    ('mancherial', 'mandamarri', 'Mandamarri', 'మందమర్రి', '4352'),
    ('mancherial', 'naspur', 'Naspur', 'నస్పూరు', '6226'),
    ('mancherial', 'nennel', 'Nennel', 'నెన్నెల్', '4331'),
    ('mancherial', 'tandur', 'Tandur', 'తాండూర్', '4332'),
    ('mancherial', 'vemanpally', 'Vemanpally', 'వేమన్ పల్లి', '4330'),
    ('medak', 'alladurg', 'Alladurg', 'అల్లాదుర్గ్', '4470'),
    ('medak', 'chegunta', 'Chegunta', 'చేగుంట', '4466'),
    ('medak', 'chilpched', 'Chilpched', 'చిలపు చెడు', '6274'),
    ('medak', 'havelighanapur', 'Havelighanapur', 'హవెలి ఘనాపూర్', '6270'),
    ('medak', 'kowdipally', 'Kowdipally', 'కౌడిపల్లి', '4480'),
    ('medak', 'kulcharam', 'Kulcharam', 'కుల్చారం', '4468'),
    ('medak', 'manoharabad', 'Manoharabad', 'మనోహరాబాద్', '6273'),
    ('medak', 'medak', 'Medak', 'మెదక్', '4456'),
    ('medak', 'narsapur', 'Narsapur', 'నర్సాపూర్', '4488'),
    ('medak', 'narsingi', 'Narsingi', 'నర్సింగి', '6272'),
    ('medak', 'nizampet', 'Nizampet', 'నిజాంపేట్', '6271'),
    ('medak', 'papannapet', 'Papannapet', 'పాపన్నపేట్', '4455'),
    ('medak', 'ramayampet', 'Ramayampet', 'రామాయంపేట', '4457'),
    ('medak', 'regode', 'Regode', 'రేగోడు', '4471'),
    ('medak', 'shankarampet-a', 'Shankarampet (A)', 'శంకరంపేట్ (ఎ)', '4454'),
    ('medak', 'shankarampet-r', 'Shankarampet (R)', 'శంకరంపేట(ఆర్)', '4467'),
    ('medak', 'shivampet', 'Shivampet', 'శివ్వంపేట్', '4487'),
    ('medak', 'tekmal', 'Tekmal', 'టేక్మాల్', '4469'),
    ('medak', 'toopran', 'Toopran', 'తూప్రాన్', '4482'),
    ('medak', 'yeldurthy', 'Yeldurthy', 'ఎల్దుర్తి', '4481'),
    ('medchal-malkajgiri', 'alwal', 'Alwal', 'అల్వాల్', '6328'),
    ('medchal-malkajgiri', 'bachupally', 'Bachupally', 'బాచ్ పల్లి', '6315'),
    ('medchal-malkajgiri', 'balanagar', 'Balanagar', 'బాలానగర్', '4517'),
    ('medchal-malkajgiri', 'gandimaisamma-dundigal', 'Gandimaisamma Dundigal', 'గండిమైసమ్మ దుండిగల్', '6316'),
    ('medchal-malkajgiri', 'ghatkesar', 'Ghatkesar', 'ఘట్కేసర్', '4523'),
    ('medchal-malkajgiri', 'kapra', 'Kapra', 'కాప్రా', '6317'),
    ('medchal-malkajgiri', 'keesara', 'Keesara', 'కీసర(M)', '4522'),
    ('medchal-malkajgiri', 'kukatpally', 'Kukatpally', 'కూకట్ పల్లి', '6327'),
    ('medchal-malkajgiri', 'malkajgiri', 'Malkajgiri', 'మల్కాజగిరి', '4521'),
    ('medchal-malkajgiri', 'medchal', 'Medchal', 'మేడ్చల్(M)', '4519'),
    ('medchal-malkajgiri', 'medipally', 'Medipally', 'మేడిపల్లి', '6318'),
    ('medchal-malkajgiri', 'muduchinthalapally', 'Muduchinthalapally', 'Muduchinthalapally మండలం', '6671'),
    ('medchal-malkajgiri', 'qutballapur', 'Qutballapur', 'ఖుతుబుల్లాపూర్', '4518'),
    ('medchal-malkajgiri', 'shamirpet', 'Shamirpet', 'షామీర్ పేట్', '4520'),
    ('medchal-malkajgiri', 'uppal', 'Uppal', 'ఉప్పల్', '4524'),
    ('mulugu', 'eturunagaram', 'Eturunagaram', 'ఏటూర్ నాగారం', '4685'),
    ('mulugu', 'govindaraopet', 'Govindaraopet', 'గోవిందరావుపేట', '4688'),
    ('mulugu', 'kannaigudem', 'Kannaigudem', 'కన్నాయిగూడెం', '6251'),
    ('mulugu', 'mangapet', 'Mangapet', 'మంగపేట', '4686'),
    ('mulugu', 'mulug', 'Mulug', 'ములుగు', '4689'),
    ('mulugu', 'tadvai', 'Tadvai', 'తాడ్వాయి (సమ్మక్క సారక్క)', '4687'),
    ('mulugu', 'venkatapur', 'Venkatapur', 'వెంకటాపూర్', '4684'),
    ('mulugu', 'venkatapuram', 'Venkatapuram', 'వెంకటాపురం', '4724'),
    ('mulugu', 'wajedu', 'Wajedu', 'వాజేడు', '4723'),
    ('nagarkurnool', 'achampet', 'Achampet', 'అచ్చం పేట', '4579'),
    ('nagarkurnool', 'amrabad', 'Amrabad', 'అమ్రాబాద్', '4578'),
    ('nagarkurnool', 'balmoor', 'Balmoor', 'బల్మూర్', '4597'),
    ('nagarkurnool', 'bijinapally', 'Bijinapally', 'బిజినేపల్లి', '4584'),
    ('nagarkurnool', 'charakonda', 'Charakonda', 'చారకోండ', '6293'),
    ('nagarkurnool', 'kalwakurthy', 'Kalwakurthy', 'కల్వకుర్తి', '4576'),
    ('nagarkurnool', 'kodair', 'Kodair', 'కోడేరు', '4600'),
    ('nagarkurnool', 'kollapur', 'Kollapur', 'కొల్లాపూర్', '4609'),
    ('nagarkurnool', 'lingal', 'Lingal', 'లింగాల్', '4598'),
    ('nagarkurnool', 'nagarkurnool', 'Nagarkurnool', 'నాగర్ కర్నూల్', '4583'),
    ('nagarkurnool', 'padara', 'Padara', 'పదర', '6294'),
    ('nagarkurnool', 'peddakothapally', 'Peddakothapally', 'పెద్దకొత్తపల్లి', '4599'),
    ('nagarkurnool', 'pentlavelli', 'Pentlavelli', 'పెంట్లవెల్లి', '6292'),
    ('nagarkurnool', 'tadoor', 'Tadoor', 'తాడూరు', '4582'),
    ('nagarkurnool', 'telkapally', 'Telkapally', 'తెల్కపల్లి', '4581'),
    ('nagarkurnool', 'thimmajipet', 'Thimmajipet', 'తిమ్మాజీపేట్', '4575'),
    ('nagarkurnool', 'uppununthala', 'Uppununthala', 'ఉప్పునుంతల', '4580'),
    ('nagarkurnool', 'urkonda', 'Urkonda', 'ఊర్కొండ', '6295'),
    ('nagarkurnool', 'vangoor', 'Vangoor', 'వంగూరు', '4577'),
    ('nagarkurnool', 'veldanda', 'Veldanda', 'వేల్దండ', '4565'),
    ('nalgonda', 'adavidevulapalli', 'Adavidevulapalli', 'అడవిదేవులపల్లి', '6304'),
    ('nalgonda', 'anumula', 'Anumula', 'అనుముల', '4660'),
    ('nalgonda', 'chandampeta', 'ChandamPeta', 'చందంపేట', '4652'),
    ('nalgonda', 'chandur', 'Chandur', 'చండూరు', '4655'),
    ('nalgonda', 'chinthapally', 'ChinthaPally', 'చింతపల్లి', '4650'),
    ('nalgonda', 'chityal', 'Chityal', 'చిట్యాల', '4633'),
    ('nalgonda', 'dameracherla', 'Dameracherla', 'దామెరచర్ల', '4663'),
    ('nalgonda', 'devarakonda', 'Devarakonda', 'దేవరకొండ', '4653'),
    ('nalgonda', 'gundlapally', 'GundlaPally', 'గుండ్లపల్లి', '4651'),
    ('nalgonda', 'gurrampode', 'Gurrampode', 'గుర్రంపూడ్', '4657'),
    ('nalgonda', 'kanagal', 'Kanagal', 'కనగల్', '4656'),
    ('nalgonda', 'kattangur', 'Kattangur', 'కట్టంగూర్', '4635'),
    ('nalgonda', 'kethepally', 'KethePally', 'కేతేపల్లి', '4637'),
    ('nalgonda', 'kondamallepally', 'Kondamallepally', 'కౌండమల్లెపల్లి', '6307'),
    ('nalgonda', 'madugulapally', 'Madugulapally', 'మడుగుల పల్లె', '6305'),
    ('nalgonda', 'marriguda', 'Marriguda', 'మర్రిగూడ', '4649'),
    ('nalgonda', 'miryalaguda', 'Miryalaguda', 'మిర్యాలగూడ', '4664'),
    ('nalgonda', 'munugode', 'Munugode', 'మునుగోడు', '4647'),
    ('nalgonda', 'nakrekal', 'Nakrekal', 'నకిరేకల్', '4636'),
    ('nalgonda', 'nalgonda', 'Nalgonda', 'నల్లగొండ', '4646'),
    ('nalgonda', 'nampally', 'Nampally', 'నాంపల్లి', '4654'),
    ('nalgonda', 'narketpally', 'Narketpally', 'నార్కటుపల్లి', '4634'),
    ('nalgonda', 'neredugommu', 'Neredugommu', 'నేరెడుగొమ్ము', '6308'),
    ('nalgonda', 'nidmanoor', 'Nidmanoor', 'నిడమనూరు', '4661'),
    ('nalgonda', 'pedda-adesherlapally', 'Pedda Adesherlapally', 'పెద్ద అడిశర్లపల్లి', '4658'),
    ('nalgonda', 'peddavoora', 'Peddavoora', 'పెద్దవూర', '4659'),
    ('nalgonda', 'shaligouraram', 'ShaliGouraram', 'శాలిగౌరారం', '4624'),
    ('nalgonda', 'thipparthy', 'Thipparthy', 'తిప్పర్తి', '4645'),
    ('nalgonda', 'tirumalagiri-sagar', 'Tirumalagiri Sagar', 'తిరుమలగిరి సాగర్', '6306'),
    ('nalgonda', 'tripuraram', 'Tripuraram', 'త్రిపురారం', '4662'),
    ('nalgonda', 'vemulapally', 'Vemulapally', 'వేములపల్లి', '4644'),
    ('narayanpet', 'damargidda', 'Damargidda', 'దామర్ గిద్ద', '4553'),
    ('narayanpet', 'dhanwada', 'Dhanwada', 'దన్వాడ', '4572'),
    ('narayanpet', 'kosgi', 'Kosgi', 'కోస్గి', '4551'),
    ('narayanpet', 'krishna', 'Krishna', 'క్రిష్ణ', '6264'),
    ('narayanpet', 'maddur', 'Maddur', 'మద్దూర్', '4554'),
    ('narayanpet', 'maganoor', 'Maganoor', 'మాగనూరు', '4590'),
    ('narayanpet', 'makthal', 'Makthal', 'మఖ్తల్', '4589'),
    ('narayanpet', 'marikal', 'Marikal', 'మరికల్', '6263'),
    ('narayanpet', 'narayanpet', 'Narayanpet', 'నారయణ పేట్', '4570'),
    ('narayanpet', 'narwa', 'Narwa', 'నర్వ', '4588'),
    ('narayanpet', 'utkoor', 'Utkoor', 'ఉట్కురు', '4571'),
    ('nirmal', 'basar', 'Basar', 'బాసర', '6205'),
    ('nirmal', 'bhainsa', 'Bhainsa', 'భైంసా', '4339'),
    ('nirmal', 'dasturabad', 'Dasturabad', 'దస్తూరబాద్', '6207'),
    ('nirmal', 'dilawarpur', 'Dilawarpur', 'దిలావర్ పూర్', '4343'),
    ('nirmal', 'kaddam-peddur', 'Kaddam Peddur', 'కడం పెద్దూర్', '4335'),
    ('nirmal', 'khanapur', 'Khanapur', 'ఖానాపూర్', '4347'),
    ('nirmal', 'kubeer', 'Kubeer', 'కుబీర్', '4338'),
    ('nirmal', 'kuntala', 'Kuntala', 'కుంటాల', '4337'),
    ('nirmal', 'laxmanchanda', 'Laxmanchanda', 'లక్ష్మణ్ చాంద', '4345'),
    ('nirmal', 'lokeswaram', 'Lokeswaram', 'లోకేశ్వరం', '4342'),
    ('nirmal', 'mamada', 'Mamada', 'మామడ', '4346'),
    ('nirmal', 'mudhole', 'Mudhole', 'ముధోల్', '4341'),
    ('nirmal', 'narsapur-g', 'Narsapur G', 'నర్సాపూర్ (జి)', '6208'),
    ('nirmal', 'nirmal-rural', 'Nirmal Rural', 'నిర్మల్ (రూరల్)', '6210'),
    ('nirmal', 'nirmal-u', 'Nirmal U', 'నిర్మల్ (యు)', '4344'),
    ('nirmal', 'pembi', 'Pembi', 'పెంబి', '6206'),
    ('nirmal', 'sarangapur', 'Sarangapur', 'సారంగపూర్', '4336'),
    ('nirmal', 'soan', 'Soan', 'సోన్', '6209'),
    ('nirmal', 'tanoor', 'Tanoor', 'తానూర్', '4340'),
    ('nizamabad', 'armoor', 'Armoor', 'ఆర్మూర్', '4360'),
    ('nizamabad', 'balkonda', 'Balkonda', 'బాల్కోండ', '4361'),
    ('nizamabad', 'bheemgal', 'Bheemgal', 'భీంగల్', '4364'),
    ('nizamabad', 'bodhan', 'Bodhan', 'బోధన్', '4370'),
    ('nizamabad', 'chandur', 'Chandur', 'Chandur మండలం', '6669'),
    ('nizamabad', 'dharpally', 'Dharpally', 'ధర్ పల్లి', '4378'),
    ('nizamabad', 'dichpally', 'Dichpally', 'డిచ్ పల్లి', '4377'),
    ('nizamabad', 'indalwai', 'Indalwai', 'ఇందల్ వాయి', '6236'),
    ('nizamabad', 'jakranpally', 'Jakranpally', 'జక్రాన్ పల్లి', '4366'),
    ('nizamabad', 'kammarpally', 'Kammarpally', 'కమ్మర్ పల్లి', '4363'),
    ('nizamabad', 'kotagiri', 'Kotagiri', 'కోటగిరి', '4371'),
    ('nizamabad', 'makloor', 'Makloor', 'మక్లూర్', '4367'),
    ('nizamabad', 'mendora', 'Mendora', 'మెండొర', '6237'),
    ('nizamabad', 'morthad', 'Morthad', 'మోర్తాడ్', '4362'),
    ('nizamabad', 'mosara', 'Mosara', 'Mosara మండలం', '6668'),
    ('nizamabad', 'mugpal', 'Mugpal', 'ముగ్పాల్', '6235'),
    ('nizamabad', 'mupkal', 'Mupkal', 'ముప్ కాల్', '6238'),
    ('nizamabad', 'nandipet', 'Nandipet', 'నందిపేట్', '4359'),
    ('nizamabad', 'navipet', 'Navipet', 'నవీపేట్', '4358'),
    ('nizamabad', 'nizamabad-north', 'Nizamabad North', 'నిజామాబాదు నార్త్', '4368'),
    ('nizamabad', 'nizamabad-rural', 'Nizamabad Rural', 'నిజామాబాదు రూరల్', '6233'),
    ('nizamabad', 'nizamabad-south', 'Nizamabad South', 'నిజామాబాదు సౌత్', '6385'),
    ('nizamabad', 'renjal', 'Renjal', 'రేంజల్', '4357'),
    ('nizamabad', 'rudrur', 'Rudrur', 'రుద్రూర్', '6240'),
    ('nizamabad', 'sirikonda', 'Sirikonda', 'సిరికోండ', '4379'),
    ('nizamabad', 'vailpoor', 'Vailpoor', 'వేల్పూర్', '4365'),
    ('nizamabad', 'varni', 'Varni', 'వర్ని', '4376'),
    ('nizamabad', 'yedapally', 'Yedapally', 'ఎడపల్లి', '4369'),
    ('nizamabad', 'yergatla', 'Yergatla', 'ఎర్ గట్ల', '6239'),
    ('peddapalli', 'anthergaon', 'Anthergaon', 'అంతర్ గాం', '6214'),
    ('peddapalli', 'dharmaram', 'Dharmaram', 'ధర్మారం', '4411'),
    ('peddapalli', 'eligaid', 'Eligaid', 'ఎలిగేడు', '4410'),
    ('peddapalli', 'julapalli', 'Julapalli', 'జూలపల్లి', '4409'),
    ('peddapalli', 'kamanpur', 'Kamanpur', 'కమాన్ పూర్', '4400'),
    ('peddapalli', 'manthani', 'Manthani', 'మంథని', '4401'),
    ('peddapalli', 'mutharam-manthani', 'Mutharam (Manthani)', 'ముత్తారం(మంథని)', '4406'),
    ('peddapalli', 'odela', 'Odela', 'ఓదెల', '4426'),
    ('peddapalli', 'palakurthy', 'Palakurthy', 'పాలకుర్తి', '6215'),
    ('peddapalli', 'peddapalli', 'Peddapalli', 'పెద్దపల్లి', '4408'),
    ('peddapalli', 'ramagiri', 'Ramagiri', 'రామగిరి', '6216'),
    ('peddapalli', 'ramagundam', 'Ramagundam', 'రామగుండం', '4399'),
    ('peddapalli', 'srirampur', 'Srirampur', 'శ్రీ రాంపూర్', '4407'),
    ('peddapalli', 'sulthanabad', 'Sulthanabad', 'సుల్తానాబాద్', '4425'),
    ('rajanna-sircilla', 'boinpalli', 'Boinpalli', 'బోయినిపల్లి', '4429'),
    ('rajanna-sircilla', 'chandurthi', 'Chandurthi', 'చందుర్తి', '4419'),
    ('rajanna-sircilla', 'gambhiraopet', 'Gambhiraopet', 'గంభీరావు పేట', '4433'),
    ('rajanna-sircilla', 'illanthakunta', 'Illanthakunta', 'ఇల్లంతకుంట', '4436'),
    ('rajanna-sircilla', 'konaraopet', 'Konaraopet', 'కోనరావు పేట', '4431'),
    ('rajanna-sircilla', 'mustabad', 'Mustabad', 'ముస్తాబాద్', '4434'),
    ('rajanna-sircilla', 'rudrangi', 'Rudrangi', 'రుద్రంగి', '6219'),
    ('rajanna-sircilla', 'sircilla', 'Sircilla', 'సిరిసిల్ల', '4435'),
    ('rajanna-sircilla', 'thangallapalli', 'Thangallapalli', 'తంగళ్ల పల్లి', '6217'),
    ('rajanna-sircilla', 'veernapalli', 'Veernapalli', 'వీర్న పల్లి', '6220'),
    ('rajanna-sircilla', 'vemulawada', 'Vemulawada', 'వేములవాడ', '4430'),
    ('rajanna-sircilla', 'vemulawada-rural', 'Vemulawada Rural', 'వేములవాడ రూరల్', '6218'),
    ('rajanna-sircilla', 'yellareddipet', 'Yellareddipet', 'యెల్లరెడ్డి పేట్', '4432'),
    ('rangareddy', 'abdullapurmet', 'Abdullapurmet', 'అబ్దుల్లాపూర్మెట్', '6319'),
    ('rangareddy', 'amangal', 'Amangal', 'అమంగల్', '4563'),
    ('rangareddy', 'balapur', 'Balapur', 'బాలాపూర్', '6323'),
    ('rangareddy', 'chevella', 'Chevella', 'చేవెళ్ళ', '4529'),
    ('rangareddy', 'farooqnagar', 'Farooqnagar', 'ఫరూఖ్ నగర్', '4559'),
    ('rangareddy', 'gandipet', 'Gandipet', 'గండిపెట్', '6320'),
    ('rangareddy', 'hayathnagar', 'Hayathnagar', 'హయత్ నగర్', '4525'),
    ('rangareddy', 'ibrahimpatnam', 'Ibrahimpatnam', 'ఇబ్రహీంపట్నం', '4546'),
    ('rangareddy', 'jilled-chowdergudem', 'Jilled Chowdergudem', 'జిల్లెడ్ చౌదెర్గూడెం', '6322'),
    ('rangareddy', 'kadthal', 'Kadthal', 'కడ్తాల్', '6324'),
    ('rangareddy', 'kandukur', 'Kandukur', 'కందుకూరు', '4545'),
    ('rangareddy', 'keshampet', 'Keshampet', 'కేశంపేట', '4561'),
    ('rangareddy', 'kondurg', 'Kondurg', 'కోందుర్గు', '4558'),
    ('rangareddy', 'kothur', 'Kothur', 'కోత్తూర్', '4560'),
    ('rangareddy', 'madgul', 'Madgul', 'మాడ్గుల', '4564'),
    ('rangareddy', 'maheshwaram', 'Maheshwaram', 'మహేశ్వరం', '4544'),
    ('rangareddy', 'manchal', 'Manchal', 'మంచాల్', '4547'),
    ('rangareddy', 'moinabad', 'Moinabad', 'మోయినా బాద్', '4528'),
    ('rangareddy', 'nandigama', 'Nandigama', 'నందిగామ', '6321'),
    ('rangareddy', 'rajendranagar', 'Rajendranagar', 'రాజేంద్ర నగర్', '4527'),
    ('rangareddy', 'saroornagar', 'Saroornagar', 'సరూర్ నగర్', '4526'),
    ('rangareddy', 'serilingampally', 'Serilingampally', 'శేరిలింగంపల్లి', '4516'),
    ('rangareddy', 'shabad', 'Shabad', 'షాబాద్', '4542'),
    ('rangareddy', 'shamshabad', 'Shamshabad', 'శంషాబాద్', '4543'),
    ('rangareddy', 'shankarpalle', 'Shankarpalle', 'శంకర్ పల్లి', '4515'),
    ('rangareddy', 'thalakondapally', 'Thalakondapally', 'తలకోండపల్లి', '4562'),
    ('rangareddy', 'yacharam', 'Yacharam', 'యాచారం', '4548'),
    ('sangareddy', 'ameenpur', 'Ameenpur', 'అమిన్ పూర్', '6276'),
    ('sangareddy', 'andole', 'Andole', 'ఆందోల్', '4479'),
    ('sangareddy', 'gummadidala', 'Gummadidala', 'గుమ్మడిదల', '6277'),
    ('sangareddy', 'hathnoora', 'Hathnoora', 'హత్నూర', '4489'),
    ('sangareddy', 'jharasangam', 'Jharasangam', 'ఝరాసంఘం', '4476'),
    ('sangareddy', 'jinnaram', 'Jinnaram', 'జిన్నారం', '4493'),
    ('sangareddy', 'kalher', 'Kalher', 'కల్హేర్', '4453'),
    ('sangareddy', 'kandi', 'Kandi', 'కంది', '6275'),
    ('sangareddy', 'kangti', 'Kangti', 'కంగ్టి', '4450'),
    ('sangareddy', 'kohir', 'Kohir', 'కోహిర్', '4475'),
    ('sangareddy', 'kondapur', 'Kondapur', 'కొండాపూర్', '4491'),
    ('sangareddy', 'manoor', 'Manoor', 'మనూర్', '4451'),
    ('sangareddy', 'mogudampally', 'Mogudampally', 'మొగుడంపల్లి', '6278'),
    ('sangareddy', 'munipally', 'Munipally', 'మునిపల్లి', '4477'),
    ('sangareddy', 'nagalgidda', 'Nagalgidda', 'నాగల్ గిద్ద', '6280'),
    ('sangareddy', 'narayankhed', 'Narayankhed', 'నారాయణఖేడ్', '4452'),
    ('sangareddy', 'nyalkal', 'Nyalkal', 'న్యాల్ కల్', '4473'),
    ('sangareddy', 'patancheru', 'Patancheru', 'పటాన్ చెరు', '4494'),
    ('sangareddy', 'pulkal', 'Pulkal', 'పుల్కల్', '4478'),
    ('sangareddy', 'raikode', 'Raikode', 'రాయకోడ్', '4472'),
    ('sangareddy', 'ramchandrapuram', 'Ramchandrapuram', 'రామచంద్రాపురం', '4495'),
    ('sangareddy', 'sadasivpet', 'Sadasivpet', 'సదాశివపేట్', '4490'),
    ('sangareddy', 'sangareddy', 'Sangareddy', 'సంగారెడ్డి', '4492'),
    ('sangareddy', 'sirgapoor', 'Sirgapoor', 'సిర్గాపూర్', '6279'),
    ('sangareddy', 'vatpally', 'Vatpally', 'వట్ పల్లి', '6291'),
    ('sangareddy', 'zahirabad', 'Zahirabad', 'జహీరాబాద్', '4474'),
    ('siddipet', 'akkannapet', 'Akkannapet', 'అక్కన్నపేట', '6285'),
    ('siddipet', 'bejjanki', 'Bejjanki', 'బెజ్జంకి', '4437'),
    ('siddipet', 'cherial', 'Cherial', 'చేర్యాల', '4672'),
    ('siddipet', 'chinnakodur', 'Chinnakodur', 'చిన్నకోడూర్', '4460'),
    ('siddipet', 'doultabad', 'Doultabad', 'దౌల్తాబాద్', '4465'),
    ('siddipet', 'dubbak', 'Dubbak', 'దుబ్బాక', '4458'),
    ('siddipet', 'gajwel', 'Gajwel', 'గజ్వెల్', '4483'),
    ('siddipet', 'husnabad', 'Husnabad', 'హుస్నాబాద్', '4444'),
    ('siddipet', 'jagdevpur', 'Jagdevpur', 'జగదేవ్ పూర్', '4484'),
    ('siddipet', 'koheda', 'Koheda', 'కోహెడ', '4443'),
    ('siddipet', 'komuravelli', 'Komuravelli', 'కొమురవెల్లి', '6284'),
    ('siddipet', 'kondapak', 'Kondapak', 'కొండపాక', '4462'),
    ('siddipet', 'maddur', 'Maddur', 'మద్దూరు', '4673'),
    ('siddipet', 'markook', 'Markook', 'మర్కుక్', '6282'),
    ('siddipet', 'mirdoddi', 'Mirdoddi', 'మిర్ దొడ్డి', '4464'),
    ('siddipet', 'mulug', 'Mulug', 'ములుగు', '4486'),
    ('siddipet', 'nangnoor', 'Nangnoor', 'నంగునూరు', '4461'),
    ('siddipet', 'narayanaraopet', 'Narayanaraopet', 'Narayanaraopet మండలం', '6670'),
    ('siddipet', 'raipole', 'Raipole', 'రాయపోల్', '6283'),
    ('siddipet', 'siddipet-rural', 'Siddipet Rural', 'సిద్దిపేట (రూరల్)', '6281'),
    ('siddipet', 'siddipet-urban', 'Siddipet Urban', 'సిద్దిపేట (అర్బన్)', '4459'),
    ('siddipet', 'thoguta', 'Thoguta', 'తొగుట', '4463'),
    ('siddipet', 'wargal', 'Wargal', 'వర్గల్', '4485'),
    ('suryapet', 'ananthagiri', 'Ananthagiri', 'అనంతగిరి', '6302'),
    ('suryapet', 'atmakur-s', 'Atmakur (S)', 'ఆత్మకూరు (సూ)', '4622'),
    ('suryapet', 'chilkur', 'Chilkur', 'చిలుకూరు', '4667'),
    ('suryapet', 'chinthalapalem', 'Chinthalapalem', 'చింతలపాలెం (మల్లారెడ్డి గూడెం)', '6303'),
    ('suryapet', 'chivemla', 'Chivemla', 'చివ్వేంల', '4639'),
    ('suryapet', 'garidepally', 'GaridePally', 'గరిడేపల్లి', '4666'),
    ('suryapet', 'huzurnagar', 'Huzurnagar', 'హుజుర్ నగర్', '4669'),
    ('suryapet', 'jajireddygudem', 'JajiReddyGudem', 'జాజిరెడ్డిగూడెం', '4623'),
    ('suryapet', 'kodad', 'Kodad', 'కోదాడ్', '4668'),
    ('suryapet', 'maddirala', 'Maddirala', 'మద్దిరాల', '6300'),
    ('suryapet', 'mattampally', 'MattamPally', 'మట్టంపల్లి', '4670'),
    ('suryapet', 'mellachervu', 'MellaChervu', 'మేళ్ళచెరువు', '4671'),
    ('suryapet', 'mothey', 'Mothey', 'మోతె', '4640'),
    ('suryapet', 'munagala', 'Munagala', 'మునగాల', '4642'),
    ('suryapet', 'nadigudem', 'Nadigudem', 'నడిగూడెం', '4641'),
    ('suryapet', 'nagaram', 'Nagaram', 'నాగారం', '6298'),
    ('suryapet', 'nereducherla', 'Nereducherla', 'నేరేడ్ చర్ల', '4665'),
    ('suryapet', 'nuthanakal', 'Nuthanakal', 'నూతనకల్లు', '4621'),
    ('suryapet', 'palakeedu', 'Palakeedu', 'పాలకీడు', '6301'),
    ('suryapet', 'penpahad', 'Penpahad', 'పెనుపహడ్', '4643'),
    ('suryapet', 'suryapet', 'Suryapet', 'సూర్యాపేట', '4638'),
    ('suryapet', 'thirumalagiri', 'Thirumalagiri', 'తిర్మలగిరి', '4619'),
    ('suryapet', 'thungaturthy', 'Thungaturthy', 'తుంగతుర్తి', '4620'),
    ('vikarabad', 'bantwaram', 'Bantwaram', 'బంట్వారం', '4532'),
    ('vikarabad', 'basheerabad', 'Basheerabad', 'బషీరాబాద్', '4535'),
    ('vikarabad', 'bomaraspeta', 'Bomaraspeta', 'బోంరాస్ పేట', '4550'),
    ('vikarabad', 'dharur', 'Dharur', 'ధారూరు', '4531'),
    ('vikarabad', 'doma', 'Doma', 'దోమ(M)', '4537'),
    ('vikarabad', 'doulathabad', 'Doulathabad', 'దౌలతాబాద్', '4552'),
    ('vikarabad', 'kodangal', 'Kodangal', 'కోడంగల్', '4549'),
    ('vikarabad', 'kotepally', 'Kotepally', 'కోటెపల్లి', '6312'),
    ('vikarabad', 'kulkacharla', 'Kulkacharla', 'కుల్కచర్ల(M)', '4539'),
    ('vikarabad', 'marpalle', 'Marpalle', 'మర్పల్లి(M)', '4512'),
    ('vikarabad', 'mominpet', 'Mominpet', 'మోమిన్ పేట్', '4513'),
    ('vikarabad', 'nawabpet', 'Nawabpet', 'నవాబ్ పేట్', '4514'),
    ('vikarabad', 'pargi', 'Pargi', 'పరిగి', '4540'),
    ('vikarabad', 'peddemul', 'Peddemul', 'పెద్దముల్', '4533'),
    ('vikarabad', 'pudur', 'Pudur', 'పూడూర్(M)', '4541'),
    ('vikarabad', 'tandur', 'Tandur', 'తాండూర్', '4534'),
    ('vikarabad', 'vikarabad', 'Vikarabad', 'వికారాబాద్', '4530'),
    ('vikarabad', 'yelal', 'Yelal', 'యాలాల్(M)', '4536'),
    ('wanaparthy', 'amarchintha', 'Amarchintha', 'అమరచింత', '6290'),
    ('wanaparthy', 'atmakur', 'Atmakur', 'ఆత్మకూర్', '4592'),
    ('wanaparthy', 'chinnambavi', 'Chinnambavi', 'చిన్నంబావి', '6287'),
    ('wanaparthy', 'ghanpur', 'Ghanpur', 'ఘనపూర్', '4585'),
    ('wanaparthy', 'gopalpeta', 'Gopalpeta', 'గోపాల్ పేట', '4596'),
    ('wanaparthy', 'kothakota', 'Kothakota', 'కోత్తకోట', '4593'),
    ('wanaparthy', 'madanapur', 'Madanapur', 'మదనాపురం', '6289'),
    ('wanaparthy', 'pangal', 'Pangal', 'పాన్ గల్', '4601'),
    ('wanaparthy', 'pebbair', 'Pebbair', 'పెబ్బెర్', '4602'),
    ('wanaparthy', 'peddamandadi', 'Peddamandadi', 'పెద్ద మందడి', '4594'),
    ('wanaparthy', 'revally', 'Revally', 'రేవల్లి', '6286'),
    ('wanaparthy', 'srirangapur', 'Srirangapur', 'శ్రీ రంగాపూర్', '6288'),
    ('wanaparthy', 'wanaparthy', 'Wanaparthy', 'వనపర్తి', '4595'),
    ('wanaparthy', 'weepangandla', 'Weepangandla', 'వీపన్ గండ్ల', '4608'),
    ('warangal', 'athmakur', 'Athmakur', 'ఆత్మాకూర్', '4694'),
    ('warangal', 'chennaraopet', 'Chennaraopet', 'చెన్నారావుపేట', '4712'),
    ('warangal', 'damera', 'Damera', 'దామెర', '6375'),
    ('warangal', 'duggondi', 'Duggondi', 'దుగ్గొండి', '4693'),
    ('warangal', 'geesugonda', 'Geesugonda', 'గీసుగొండ', '4707'),
    ('warangal', 'khanapur', 'Khanapur', 'ఖానాపూర్', '4709'),
    ('warangal', 'nadikula', 'Nadikula', 'Nadikula మండలం', '6547'),
    ('warangal', 'nallabelli', 'Nallabelli', 'నల్లబెల్లి', '4692'),
    ('warangal', 'narsampet', 'Narsampet', 'నర్సంపేట', '4708'),
    ('warangal', 'nekkonda', 'Nekkonda', 'నెక్కొండ', '4713'),
    ('warangal', 'parkal', 'Parkal', 'పర్కాల', '4679'),
    ('warangal', 'parvathagiri', 'Parvathagiri', 'పర్వతగిరి', '4714'),
    ('warangal', 'rayaparthy', 'Rayaparthy', 'రాయపర్తి', '4703'),
    ('warangal', 'sangem', 'Sangem', 'సంగెం', '4705'),
    ('warangal', 'shayampet', 'Shayampet', 'శాయంపేట్', '4691'),
    ('warangal', 'wardhannapet', 'Wardhannapet', 'వర్దన్నపేట', '4704'),
    ('yadadri-bhuvanagiri', 'adda-guduru', 'Adda Guduru', 'అడ్డగూడూరు', '6310'),
    ('yadadri-bhuvanagiri', 'alair', 'Alair', 'ఆలేరు', '4617'),
    ('yadadri-bhuvanagiri', 'atmakur-m', 'Atmakur (M)', 'ఆత్మకూరు (మో)', '4626'),
    ('yadadri-bhuvanagiri', 'b-pochampally', 'B Pochampally', 'బి.పోచంపల్లి', '4630'),
    ('yadadri-bhuvanagiri', 'bhongir', 'Bhongir', 'భూవనగిరి', '4628'),
    ('yadadri-bhuvanagiri', 'bibinagar', 'Bibinagar', 'బీబినగర్', '4629'),
    ('yadadri-bhuvanagiri', 'bommalaramaram', 'Bommalaramaram', 'బొమ్మలరామారం', '4613'),
    ('yadadri-bhuvanagiri', 'choutuppal', 'Choutuppal', 'చౌట్టుప్పల్', '4631'),
    ('yadadri-bhuvanagiri', 'motakonduru', 'Motakonduru', 'మూటకొండూరు', '6309'),
    ('yadadri-bhuvanagiri', 'mothkur', 'Mothkur', 'మోతుకూరు', '4625'),
    ('yadadri-bhuvanagiri', 'narayanpur', 'Narayanpur', 'నారాయణపూర్', '4648'),
    ('yadadri-bhuvanagiri', 'rajapeta', 'Rajapeta', 'రాజాపేట', '4615'),
    ('yadadri-bhuvanagiri', 'ramannapet', 'Ramannapet', 'రామన్నపేట', '4632'),
    ('yadadri-bhuvanagiri', 'thurkapally', 'Thurkapally', 'తుర్కపల్లి', '4614'),
    ('yadadri-bhuvanagiri', 'valigonda', 'Valigonda', 'వలిగొండ', '4627'),
    ('yadadri-bhuvanagiri', 'yadagirigutta', 'Yadagirigutta', 'యాదగిరి గుట్ట', '4616')
)
INSERT INTO mandals (
  district_id, slug, name_en, name_te
)
SELECT d.id, v.slug, v.name_en, v.name_te
FROM v
JOIN d ON d.slug = v.district_slug
ON CONFLICT (district_id, slug) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_te = EXCLUDED.name_te;
